package clases;

/**
 * Permite visualizar el contenido de un Listado. Framework: Swing.
 * El contenido de esta clase fue generado con NetBeans para dise�ar el JFrame, y luego levantado desde BlueJ. Se 
 * mantuvieron los agregados de comentarios y la forma del c�digo fuente tal como NetBeans los gener�, para 
 * comprender mejor su uso.
 * @author  Ing. Valerio Frittelli
 * @version Mayo de 2004
 */
public class VentanaMostrar extends javax.swing.JFrame {
    
    /** Creates new form VentanaMostrar */
    public VentanaMostrar(Listado lis) {
        listado = lis;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jTextArea1 = new javax.swing.JTextArea(listado.toString());
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setTitle("Datos del Listado");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(102, 204, 255));
        jTextArea1.setEditable(false);
        jTextArea1.setBorder(new javax.swing.border.EtchedBorder(java.awt.Color.lightGray, java.awt.Color.gray));
        getContentPane().add(jTextArea1);
        jTextArea1.setBounds(0, 0, 399, 160);

        jButton1.setText("OK");
        jButton1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton1);
        jButton1.setBounds(170, 250, 71, 23);

        setSize(400,330);
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false); 
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitForm
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
    private Listado listado;
    
}
